apiVersion: apps/v1
kind: Deployment
metadata:
  name:  L01-go-echo
  namespace: default
  labels:
    name:  L01-go-echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo 
    spec:
      containers:
      - name: echo-container
        image: hashicorp/http-echo
        args:
          - "-text=Hello from k8s and Go"
        ports:
        - containerPorts: 5678