apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  type: LoadBalancer # Das erstellt eine echte Ã¶ffentliche Azure IP
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: echo
